admin_user_name = "admin"
admin_password = "admin"
admin_tenant_name = "admin"
admin_auth_url = "http://localhost:5000/v3"
admin_domain_name = "Default"
admin_project_domain_name = "Default"

user_user_name = "churros"
user_user_password = "churr0s"
user_tenant_name = "churros"
user_auth_url = "http://localhost:5000/v3"
